apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-manager-role
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{ include "common.labels" . | indent 6 }}
rules:
  # Cert-controller is using get,list and watch verbs on secrets
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "list", "get", "watch" ]
  # Allow only to update azure-defender-cert secret - cert controller.
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "list", "watch", "update", "get" ]
    resourceNames: [ "{{ .Values.AzDProxy.prefixResourceDeployment }}-cert" ]
  # Cert-controller is using get,list and watch verbs on secrets
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "mutatingwebhookconfigurations" ]
    verbs: [ "get", "list", "watch" ]
  # Allow all verbs only on azure-defender-proxy-mutating-webhook-configuration MutatingWebhookConfiguration - cert controller.
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "mutatingwebhookconfigurations" ]
    verbs: [ "create","delete","get","list","patch","update","watch" ]
    resourceNames: [ "{{ .Values.AzDProxy.prefixResourceDeployment }}-mutating-webhook-configuration" ]