apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-defender-proxy-manager-rolebinding
  labels:
    app: '{{ template "azdproxy.name" . }}'
    chart: '{{ template "azdproxy.name" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
    admission.azdproxy.sh/ignore: no-self-managing # This field assigned in order to verify that this resource won't be mutated by azdproxy
roleRef:
  name: azure-defender-proxy-manager-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: azure-defender-proxy-admin
  namespace: '{{ .Release.Namespace }}'
  kind: ServiceAccount