apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.AzDProxy.prefixResourceDeployment }}-manager-rolebinding
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{ include "common.labels" . | indent 4 }}
roleRef:
  name: {{ .Values.AzDProxy.prefixResourceDeployment }}-manager-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: {{ .Values.AzDProxy.prefixResourceDeployment }}-admin
    namespace: '{{ .Release.Namespace }}'
    kind: ServiceAccount