# Default Configurations for AzureDefender-K8S-InClusterDefense.
# This is a ConfigMap file.
# Declare variables to be passed into configurations object of the project's files.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-config
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{ include "common.labels" . | indent 6 }}
# Application's configuration settings. Arranged by project's filesystem hierarchy
data:
  appConfig.yaml: |-
    webhook:
      certRotatorConfiguration:
        secretName: "{{ .Values.azDProxy.prefixResourceDeployment }}-{{.Values.azDProxy.webhook.certRotatorConfiguration.secretName }}"
        serviceName: "{{ .Values.azDProxy.prefixResourceDeployment }}-{{.Values.azDProxy.webhook.certRotatorConfiguration.serviceName }}"
        webhookName: "{{ .Values.azDProxy.prefixResourceDeployment }}-{{.Values.azDProxy.webhook.certRotatorConfiguration.webhookName }}"
        caName: "{{ .Values.azDProxy.prefixResourceDeployment }}-{{.Values.azDProxy.webhook.certRotatorConfiguration.caName }}"
        caOrganization: "{{ .Values.azDProxy.prefixResourceDeployment }}"
        certDir: {{.Values.azDProxy.webhook.volume.mountPath | quote}}
        namespace: {{.Release.Namespace | quote}}
      managerConfiguration:
        port: {{.Values.azDProxy.service.targetPort}}
        certDir: {{.Values.azDProxy.webhook.volume.mountPath | quote}}
      serverConfiguration:
        path: {{.Values.azDProxy.webhook.mutationPath | quote}}
        enableCertRotation: {{.Values.azDProxy.webhook.serverConfiguration.enableCertRotation}}
      handlerConfiguration:
        dryRun: {{.Values.azDProxy.webhook.handlerConfiguration.runOnDryRunMode}}
    instrumentation:
      trace:
        tracerConfiguration:
          tracerLevel: {{.Values.azDProxy.instrumentation.trace.tracerConfiguration.tracerLevel }}
      tivan:
        tivanInstrumentationConfiguration:
          componentName: {{ .Chart.Name | quote}}
          mdmNamespace: {{ .Values.azDProxy.instrumentation.tivan.tivanInstrumentationConfiguration.mdmNamespace | quote}}
    azdIdentity:
      envAzureAuthorizerConfiguration:
        isLocalDevelopmentMode: {{.Values.azDProxy.deployment.isLocalDevelopment}}
        mSIClientId: {{.Values.azDProxy.azdIdentity.envAzureAuthorizerConfiguration.mSIClientId}}
    kubeletIdentity:
      envAzureAuthorizerConfiguration:
        isLocalDevelopmentMode: {{.Values.azDProxy.deployment.isLocalDevelopment}}
        mSIClientId: {{.Values.azDProxy.kubeletIdentity.envAzureAuthorizerConfiguration.mSIClientId}}
    acr:
      craneWrappersConfiguration:
        retryPolicyConfiguration:
          retryAttempts: {{ .Values.azDProxy.acr.craneWrappers.retryPolicyConfiguration.retryAttempts }}
          retryDuration: {{ .Values.azDProxy.acr.craneWrappers.retryPolicyConfiguration.retryDuration }}
    arg:
      argBaseClient:
        retryPolicyConfiguration:
          retryAttempts: {{ .Values.azDProxy.arg.argBaseClient.retryPolicyConfiguration.retryAttempts }}
          retryDuration: {{ .Values.azDProxy.arg.argBaseClient.retryPolicyConfiguration.retryDuration }}
