apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: azure-defender-proxy-mutating-webhook-configuration
  labels:
    app: '{{ template "azdproxy.name" . }}'
    chart: '{{ template "azdproxy.name" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
webhooks:
  - name: azure-defender-proxy-service.default.svc
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "pods" ]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: '{{ .Release.Namespace }}'
        name: azure-defender-proxy-service
        path: /mutate
      caBundle: Cg==
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: In
          values: [ "default" ]
    objectSelector:
      matchExpressions:
        - key: app
          operator: NotIn
          values: [ "azure-defender" ]
    failurePolicy: Fail
    admissionReviewVersions: [ "v1", "v1beta1" ]
    sideEffects: None
    timeoutSeconds: 25