# TODO Redis deployments should be updated with stable/distributed and secured version.
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-redis-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "common.labels" . | indent 4 }}
    run: redis
spec:
  ports:
    - port: {{.Values.AzDProxy.cache.redisClient.port}}
      targetPort: {{.Values.AzDProxy.cache.redisClient.targetport}}
  selector:
    run: redis