{{- $secret_name := printf "%s-redis-pass" .Values.AzDProxy.prefixResourceDeployment -}}
{{- $ReleaseNamespace := .Release.Namespace -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "common.labels" . | indent 4 }}

data:
{{ ( include "secret-data.deploy-pass" (list $secret_name $ReleaseNamespace ) ) }}