apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: '{{ .Release.Namespace }}'
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-redis-pvc
spec:
  storageClassName: {{.Values.AzDProxy.cache.pvc.storageClassName}}
  accessModes:
    # ReadWriteMany the volume can be mounted as read-write by many nodes.
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.AzDProxy.cache.pvc.storage}}