apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-redis-config
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{ include "common.labels" . | indent 6 }}
# Redis configuration file
data:
  # No ':' is needed because Redis expect the file in this format.
  # port 0 - No tls communication is allowed
  # tls-port 6379 - Port for tls communication
  redis-config: |-
    port 0
    tls-port {{.Values.AzDProxy.cache.redis.port}}
    tls-cert-file {{.Values.AzDProxy.cache.redis.secret.volume.mountPath}}/tls.crt
    tls-key-file {{.Values.AzDProxy.cache.redis.secret.volume.mountPath}}/tls.key
    tls-ca-cert-file {{.Values.AzDProxy.cache.redis.secret.volume.mountPath}}/ca.cert