apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # namespace: '{{ .Release.Namespace }}'
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # TBD
---
# TODO Redis deployments should be updated with secured version.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-{{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.app}}-deployment
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{ include "common.labels" . | indent 4 }}
spec:
  replicas: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.replicas}} # TBD
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      volumes:
        - name: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.app}}-storage
          persistentVolumeClaim:
            claimName: {{.Values.AzDProxy.prefixResourceDeployment}}-pvc
      containers:
        - name: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.app}}
          image: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.image}}
          #          ports:
          #            - containerPort: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.port}}
          volumeMounts:
            - mountPath: /data/redis
              name: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.app}}-storage
              readOnly: false
---
# TODO Redis deployments should be updated with stable/distributed and secured version.
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-{{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.app}}-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "common.labels" . | indent 4 }}
    run: redis
spec:
  ports:
    - port: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.port}}
      targetPort: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.port}}
      protocol: TCP
  selector:
    run: {{.Values.AzDProxy.cache.nonInMem.deploymentConfiguration.app}}
