{{- $secret_name := printf "%s-redis-tls-certs" .Values.AzDProxy.prefixResourceDeployment -}}
{{- $ReleaseNamespace := .Release.Namespace -}}
{{- $serviceName := .Values.AzDProxy.cache.redis.host -}}
{{- $expireDuration := .Values.AzDProxy.cache.redis.certs.expireDuration -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secret_name }}
  namespace: '{{ $ReleaseNamespace }}'
  labels:
    {{ include "common.labels" . | indent 4 }}

data:
{{ ( include "secret-data.deploy-certs" (list $secret_name $ReleaseNamespace $serviceName $expireDuration) ) }}