apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-redis-deployment
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{ include "common.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      run: redis
  replicas: {{.Values.AzDProxy.cache.redis.replicas}}
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
        # TODO : Add securityContext section.
        - name: {{.Values.AzDProxy.prefixResourceDeployment}}-redis
          image: {{.Values.AzDProxy.cache.redis.image}}
          imagePullPolicy: 'Always'
          # Configure Redis to use password
          args: ["--requirepass", "$(REDIS_PASS)"]
          # Direct redis to its config file
          command:
            - redis-server
            - "{{.Values.AzDProxy.cache.redis.mountPath}}/redis.conf"
          ports:
            - containerPort: {{.Values.AzDProxy.cache.redis.port}}
          volumeMounts:
            # redis config file
            - mountPath: {{.Values.AzDProxy.cache.redis.mountPath}}
              name: {{.Values.AzDProxy.configuration.volume.name}}
              readOnly: true
            # redis secret
            - mountPath: {{ .Values.AzDProxy.cache.redis.secret.volume.mountPath }}
              name: {{.Values.AzDProxy.cache.redis.secret.volume.name}}
              readOnly: true
          # TODO change to mount instead of env
          env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: {{.Values.AzDProxy.prefixResourceDeployment}}-redis-pass
                key: REDIS_PASS
      volumes:
        - name: {{.Values.AzDProxy.cache.redis.secret.volume.name}}
          secret:
            secretName: {{.Values.AzDProxy.prefixResourceDeployment}}-redis-tls-certs
        - name: {{.Values.AzDProxy.configuration.volume.name}}
          configMap:
            name: {{.Values.AzDProxy.prefixResourceDeployment}}-redis-config
            items:
            - key: redis-config
              path: redis.conf
