apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-cert
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "common.labels" . | indent 4 }}
