apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-admin
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "common.labels" . | indent 4 }}