apiVersion: v1
kind: Service
metadata:
  name: azure-defender-proxy-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: '{{ template "azdproxy.name" . }}'
    chart: '{{ template "azdproxy.name" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
spec:
  type: ClusterIP
  selector:
    app: '{{ template "azdproxy.name" . }}'
    chart: '{{ template "azdproxy.name" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8000
