apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-defender-proxy-admin
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: '{{ template "azdproxy.name" . }}'
    chart: '{{ template "azdproxy.name" . }}'
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'