apiVersion: v1
kind: Service
metadata:
  name: {{.Values.AzDProxy.prefixResourceDeployment}}-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    {{ include "common.labels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: 443       # Exposes the Kubernetes service on the specified port within the cluster
      targetPort: {{ .Values.AzDProxy.service.targetPort }} # The port on which the service will send requests to, the webhook will be listening on.
