{{- $secret_name := printf "%s-redis-tls-certs" .Values.AzDProxy.prefixResourceDeployment -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $secret_name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "common.labels" . | indent 4 }}

data:
{{ ( include "secret-data.deploy-certs" . ) }}