apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-defender-proxy-manager-rolebinding
  labels:
    app: azdproxy
    admission.azdproxy.sh/ignore: no-self-managing
roleRef:
  name: azure-defender-proxy-manager-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: azure-defender-proxy-admin
  namespace: default
  kind: ServiceAccount