apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-defender-proxy-manager-role
  labels:
    app: 'azure-defender'
rules:
- resources:
  - secrets # access to imagePullSecrets
  - serviceaccounts # access to imagepullSecrets
  apiGroups:
  - ''
  verbs:
  - get
  - list
  - watch
  - update
- resources:
  - customresourcedefinitions
  apiGroups:
  - apiextensions.k8s.io
  verbs:
  - get
  - list
  - watch
- resources:
  - mutatingwebhookconfigurations
  apiGroups:
  - admissionregistration.k8s.io
  verbs:
  - get
  - list
  - watch
- resources:
  - mutatingwebhookconfigurations
  apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - azure-defender-proxy-mutating-webhook-configuration
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch