apiVersion: v1
kind: Secret
metadata:
  name: azure-defender-cert
  namespace: kube-system
  labels:
    app: azdproxy
    admission.azdproxy.sh/ignore: no-self-managing # This field assigned in order to verify that this resource won't be mutated by azdproxy
