apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-defender-proxy-deployment
  labels:
    app: azure-defender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-defender
  template:
    metadata:
      labels:
        app: azure-defender
    spec:
      serviceAccountName: azure-defender-proxy-admin
      containers:
      - name: azure-defender-proxy-webhook
        image: azdproxy-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: cert
          readOnly: true
          mountPath: /certs # {"$kpt-set":"cert-dir"}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        env:
        - name: PORT
          value: "8000"
        - name: TLS
          value: "/tls"
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: azure-defender-cert