apiVersion: v1
kind: Pod
metadata:
  name: unhealthy-pod-severity
  namespace: default
  annotations:
    azuredefender.io/containers.vulnerability.scan.info: "{\"containers\":[{\"name\":\"testContainer\",\"image\":{\"name\":\"tomer.azurecr.io/core/app:4.6\",\"digest\":\"sha256:4a\"},\"scanStatus\":\"unhealthyScan\",\"scanFindings\":[{\"patchable\":true,\"id\":\"125\",\"severity\":\"Low\"},{\"patchable\":true,\"id\":\"126\",\"severity\":\"Medium\"},{\"patchable\":true,\"id\":\"127\",\"severity\":\"High\"}]}]}"
    credScan.scan.info: "{\"generatedTimestamp\":\"2021-09-21T17:36:39.7945965Z\",\"CredScanInfo\":[{\"credentialInfo\":{\"name\":\"Azure Storage Account Access Key\"},\"MatchingConfidence\":74.96325,\"ScanStatus\":\"healthy\"},{\"credentialInfo\":{\"name\":\"General Password\"},\"MatchingConfidence\":99.9,\"ScanStatus\":\"unhealthy\"}]}"
spec:
  containers:
    - name: unhealthy-container-severity
      image: alpine
