apiVersion: v1
kind: Pod
metadata:
  name: unhealthy-pod-unscanned
  namespace: default
  annotations:
    password: "dmFsdWUtMg0KDQo="

spec:
  containers:
    - name: unhealthy-container-unscanned
      image: alpine
