apiVersion: v1
kind: Pod
metadata:
  name: unhealthy-pod-severity
  namespace: default
  annotations:
    azuredefender.io/containers.vulnerability.scan.info: "{\"containers\":[{\"name\":\"testContainer\",\"image\":{\"name\":\"tomer.azurecr.io/core/app:4.6\",\"digest\":\"sha256:4a\"},\"scanStatus\":\"unhealthyScan\",\"scanFindings\":[{\"patchable\":true,\"id\":\"125\",\"severity\":\"Low\"},{\"patchable\":true,\"id\":\"126\",\"severity\":\"Medium\"},{\"patchable\":true,\"id\":\"127\",\"severity\":\"High\"}]}]}"
spec:
  containers:
    - name: unhealthy-container-severity
      image: alpine
