apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: azure-defnder-in-cluster-defense-dev
build:
  artifacts:
    # Dev Image:
    - image: blockregistrydev.azurecr.io/nicole
      context: ./
#      sync:
#        infer:
##          - '**/*'
      docker:
        dockerfile: build/Dockerfile
profiles:
  # Dev Profile
  - name: azureDefnder-in-cluster-defense-dev
    deploy:
      kubeContext: Block-InClusterDefense-Dev
      # Deploy with helm chart
      helm:
        releases:
          - name: azure-defender-in-cluster-defense-dev
            # Path to helm chart
            chartPath: charts/azdproxy
            # Choose the namespace of the deployment
            namespace: kube-system
            # Overrides the image in the helm chart with the image that was built in the build section.
            artifactOverrides:
              AzDProxy.webhook.image.name: blockregistrydev.azurecr.io/nicole
            setValues:
              AzDProxy.arg.argClientConfiguration.subscriptions: "4009f3ee-43c4-4f19-97e4-32b6f2285a68"
              AzDProxy.kubeletIdentity.envAzureAuthorizerConfiguration.mSIClientId: "c47511a0-225d-4001-a94c-2b283d8d921d"
              AzDProxy.azdIdentity.envAzureAuthorizerConfiguration.mSIClientId: "a709c74f-f350-4702-8ef5-cd5e95399458"
            # Path to dev values:
            valuesFiles:
              - ./charts/azdproxy/values.yaml
#portForward:
#  - resourceType: deployment
#    resourceName: azure-defender-proxy-deployment
#    namespace: kube-system
#    port: 8000
#    localPort: 8000 # *Optional*