apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: azure-defnder-in-cluster-defense-dev
build:
  artifacts:
    # Dev Image:
    - image: azuredefendermcrdev.azurecr.io/public/azuredefender/dev/in-cluster-defense
      context: ./
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: build/Dockerfile
profiles:
  # Dev Profile
  - name: azureDefnder-in-cluster-defense-dev
    deploy:
      kubeContext: cluster-dev
      # Deploy with helm chart
      helm:
        releases:
          - name: azure-defender-in-cluster-defense-dev
            # Path to helm chart
            chartPath: charts/azdproxy
            # Choose the namespace of the deployment
            namespace: kube-system
            # Overrides the image in the helm chart with the image that was built in the build section.
            artifactOverrides:
              AzDProxy.webhook.image.name: azuredefendermcrdev.azurecr.io/public/azuredefender/dev/in-cluster-defense
            setValues:
              AzDProxy.arg.argClientConfiguration.subscriptions: ""
              AzDProxy.kubeletIdentity.envAzureAuthorizerConfiguration.mSIClientId: ""
              AzDProxy.azdIdentity.envAzureAuthorizerConfiguration.mSIClientId: ""
            # Path to dev values:
            valuesFiles:
              - ./charts/azdproxy/values-dev.yaml