apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: azdproxy
build:
  artifacts:
    # First image: production image
    - image: blockreg.azurecr.io/azdproxy-image
      context: ./
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: build/Dockerfile
profiles:
  # Profile name:
  - name: azuredefender
    deploy:
      # Choose the context that you want to deploy to.
      kubeContext: block
      # Deploy with helm chart
      helm:
        releases:
          # Helm chart name
          - name: azdproxy
            # Path to helm chart
            chartPath: charts/azdproxy
            # Choose the namespace of the deployment
            namespace: kube-system
            # Do you want to create new namespace?
            createNamespace: false
            # Should it skip on dependency building?
            skipBuildDependencies: false
            # Overrides the image in the helm chart with the image that was built in the build section.
            artifactOverrides:
              AzDProxy.webhook.image.name: blockreg.azurecr.io/azdproxy-image
            # Path to dev values:
            valuesFiles:
              - ./charts/azdproxy/values-dev.yaml
