apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: azdproxy
build:
  artifacts:
    # First image: production image
    - image: blockregistrydev.azurecr.io/azdproxy-image
      context: ./
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: build/Dockerfile
profiles:
  # Profile name:
  - name: azuredefender
    deploy:
      kubeContext: cluster-dev
      # Deploy with helm chart
      helm:
        releases:
          - name: azdproxy
            # Path to helm chart
            chartPath: charts/azdproxy
            # Choose the namespace of the deployment
            namespace: kube-system
            # Overrides the image in the helm chart with the image that was built in the build section.
            artifactOverrides:
              AzDProxy.webhook.image.name: blockregistrydev.azurecr.io/azdproxy-image
            setValues:
              AzDProxy.arg.argClientConfiguration.subscriptions: "SUBSCRIPTION_ID"
              AzDProxy.kubeletIdentity.envAzureAuthorizerConfiguration.mSIClientId:  "AGENT_POOL_CLIENT_ID"
              AzDProxy.azdIdentity.envAzureAuthorizerConfiguration.mSIClientId: "BLOCK_CLIENT_ID"
            # Path to dev values:
            valuesFiles:
              - ./charts/azdproxy/values-dev.yaml
