apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: azdproxy
build:
  artifacts:
    - # Image for production.
    - image: blockregistrydev.azurecr.io/azdproxy-image
      context: ./
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: build/Dockerfile
        buildArgs:
          DEVOPS_TOKEN: <PUT_YOUR_PAT_HERE>
    # Image for debugging.
    - image: blockregistrydev.azurecr.io/azdproxy-image-debugging
      context: ./
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: build/Dockerfile.debug
        buildArgs:
          DEVOPS_TOKEN: <PUT_YOUR_PAT_HERE>
profiles:
  - name: azuredefender
    deploy:
      helm:
        releases:
          - name: azdproxy
            chartPath: charts/azdproxy
            valuesFiles:
              - ./charts/azdproxy/values-dev.yaml
            namespace: kube-system
            artifactOverrides:
              AzDProxy.webhook.image.name: blockregistrydev.azurecr.io/azdproxy-image
            setValues:
              AzDProxy.azdIdentity.envAzureAuthorizerConfiguration.mSIClientId: a554f933-695f-4ecf-abe4-2a7515e8c1b7
              AzDProxy.kubeletIdentity.envAzureAuthorizerConfiguration.mSIClientId: f4a700f6-e852-4cfd-8408-2ed6d3843759
