apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    gatekeeper: "ddd"
  annotations:
    lior: "[{\"image\":\"centos:7\",\"severity\":{\"High\":2,\"Low\":15,\"Medium\":10},\"status\":\"Scanned\"}]"
spec:
  containers:
    - name: alpine3
      image: alpine:3.5