// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IFreeCacheInMemCacheWrapper is an autogenerated mock type for the IFreeCacheInMemCacheWrapper type
type IFreeCacheInMemCacheWrapper struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *IFreeCacheInMemCacheWrapper) Get(key []byte) ([]byte, error) {
	ret := _m.Called(key)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value, expireSeconds
func (_m *IFreeCacheInMemCacheWrapper) Set(key []byte, value []byte, expireSeconds int) error {
	ret := _m.Called(key, value, expireSeconds)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, int) error); ok {
		r0 = rf(key, value, expireSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
