apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureDefenderBlockVulnerableImages
metadata:
  name: psp-block-vulnerable-images
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    excludedImages: {{ .Values.excludedImages }}
    excludeNonPatchable: {{ .Values.excludeNonPatchable }}
    excludedCVS: {{ .Values.excludedImages }}
    highSeverityThreshold: {{ .Values.highSeverityThreshold }}
    mediumSeverityThreshold: {{ .Values.mediumSeverityThreshold }}
    lowSeverityThreshold: {{ .Values.lowSeverityThreshold }}
