# *** NOTE: You will always be compliant with this policy if AzureDefenderInClusterDefense is not installed in your cluster.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureDefenderBlockVulnerableImages
metadata:
  name: block-vulnerable-images
spec:
  match:
    kinds:
      - apiGroups: [ "" ]
        kinds: [ "Pod" ]
  parameters:
    excludedImages: {{ .Values.excludedImages }}
    excludeNotPatchableFindings: {{ .Values.excludeNotPatchableFindings }}
    excludeFindingIDs: {{ .Values.excludeFindingIDs }}
    sevirity:
      High: {{ .Values.highSeverityThreshold }}
      Medium: {{ .Values.mediumSeverityThreshold }}
      Low: {{ .Values.lowSeverityThreshold }}