# *** NOTE: You will always be compliant with this policy if AzureDefenderInClusterDefense is not installed in your cluster.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureDefenderBlockVulnerableImages
metadata:
  name: block-vulnerable-images
spec:
  match:
  kinds:
    - apiGroups: [ "","apps" ]
      kinds: [ "Pod","Deployment","ReplicaSet","StatefulSet","DaemonSet","Job","CronJob","ReplicationController" ]
  parameters:
    excludedImages: {{ .Values.excludedImages }}
    severityThresholdForExcludingNotPatchableFindings: {{ .Values.severityThresholdForExcludingNotPatchableFindings }}
    excludeFindingIDs: {{ .Values.excludeFindingIDs }}
    severity:
      High: {{ .Values.highSeverityThreshold }}
      Medium: {{ .Values.mediumSeverityThreshold }}
      Low: {{ .Values.lowSeverityThreshold }}