# *** You will always be compliant with this policy if AzureDefenderInClusterDefense is not installed in your cluster.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureDefenderBlockVulnerableImages
metadata:
  name: block-vulnerable-images
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    excludedImages: {{ .Values.excludedImages }}
    excludeNotPatchableFindings: {{ .Values.excludeNotPatchableFindings }}
    excludeFindingIDs: {{ .Values.excludeFindingIDs }}
    highSeverityThreshold: {{ .Values.highSeverityThreshold }}
    mediumSeverityThreshold: {{ .Values.mediumSeverityThreshold }}
    lowSeverityThreshold: {{ .Values.lowSeverityThreshold }}
