// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	registry "github.com/Azure/AzureDefender-K8S-InClusterDefense/pkg/infra/registry"
	tag2digest "github.com/Azure/AzureDefender-K8S-InClusterDefense/pkg/tag2digest"
	mock "github.com/stretchr/testify/mock"
)

// ITag2DigestResolver is an autogenerated mock type for the ITag2DigestResolver type
type ITag2DigestResolver struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: imageReference, authContext
func (_m *ITag2DigestResolver) Resolve(imageReference registry.IImageReference, authContext *tag2digest.ResourceContext) (string, error) {
	ret := _m.Called(imageReference, authContext)

	var r0 string
	if rf, ok := ret.Get(0).(func(registry.IImageReference, *tag2digest.ResourceContext) string); ok {
		r0 = rf(imageReference, authContext)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(registry.IImageReference, *tag2digest.ResourceContext) error); ok {
		r1 = rf(imageReference, authContext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
