apiVersion: v1
kind: Service
metadata:
  name: azure-defender-proxy-service
spec:
  type: ClusterIP
  selector:
    app: azure-defender
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
