# A static app's configuration file. Used for local debugging.
webhook:
  certRotatorConfiguration:
    secretName: "azure-defender-proxy-cert"
    serviceName: "azure-defender-proxy-service"
    webhookName: "azure-defender-proxy-mutating-webhook-configuration"
    caName: "azure-defender-proxy-ca"
    caOrganization: "azure-defender-proxy"
    certDir: "/certs"
    namespace: "kube-system"
  managerConfiguration:
    port: 8000
    certDir: "/certs"
  serverConfiguration:
    path: "/mutate"
    enableCertRotation: true
  handlerConfiguration:
    dryRun: false
    namespace: "kube-system"
instrumentation:
  trace:
    tracerConfiguration:
      tracerLevel: 0
  tivan:
    tivanInstrumentationConfiguration:
      componentName: "azdproxy"
      mdmNamespace: "Tivan.Collector.Pods"

azdIdentity:
  envAzureAuthorizerConfiguration:
    isLocalDevelopmentMode: true
    mSIClientId: "" # This should be kept empty while you are running the service locally.

kubeletIdentity:
  envAzureAuthorizerConfiguration:
    isLocalDevelopmentMode: true
    mSIClientId: "" # This should be kept empty while you are running the service locally.

acr:
  craneWrappersConfiguration:
    retryPolicyConfiguration:
      retryAttempts: 3
      retryDuration: "10ms"

arg:
  argClientConfiguration:
    # TODO change it to dynamic subscription that will be updated in the installation script.
    subscriptions: [ "4009f3ee-43c4-4f19-97e4-32b6f2285a68" ]

  argBaseClient:
    retryPolicyConfiguration:
      retryAttempts: 3
      retryDuration: "100ms"
