# A static app's configuration file. Used for local debugging.
webhook:
  certRotatorConfiguration:
    secretName: "azure-defender-proxy-cert"
    serviceName: "azure-defender-proxy-service"
    webhookName: "azure-defender-proxy-mutating-webhook-configuration"
    caName: "azure-defender-proxy-ca"
    caOrganization: "azure-defender-proxy"
    certDir: "/certs"
    namespace: "kube-system"
  managerConfiguration:
    port: 8000
    certDir: "/certs"
  serverConfiguration:
    path: "/mutate"
    enableCertRotation: true
  handlerConfiguration:
    dryRun: false
instrumentation:
  trace:
    tracerConfiguration:
      tracerLevel: 0
  tivan:
    tivanInstrumentationConfiguration:
      componentName: "azdproxy"
      mdmNamespace: "Tivan.Collector.Pods"

azdIdentity:
  envAzureAuthorizerConfiguration:
    mSIClientId: "" # This should be kept empty while you are running the service locally.

kubeletIdentity:
  envAzureAuthorizerConfiguration:
    mSIClientId: "" # This should be kept empty while you are running the service locally.

acr:
  craneWrappersConfiguration:
    retryPolicyConfiguration:
      retryAttempts: 3
      retryDuration: 10
      timeUnit: "ms"

arg:
  argClientConfiguration:
    subscriptions: []
  argBaseClient:
    retryPolicyConfiguration:
      retryAttempts: 3
      retryDuration: 10
      timeUnit: "ms"

cache:
  nonInMem:
    deploymentConfiguration:
      app: redis
      image: redis:6
      replicas: 1
    client:
      clientConfiguration:
        address: "azure-defender-proxy-redis-service:6379"
        tables:
          argDataProviderCacheTable: 0
          tag2digestCacheTable: 1
      retryPolicyConfiguration:
        retryAttempts: 3
        retryDuration: 10
        timeUnit: "ms"
  inMem:
    tokensCacheConfiguration:
      cacheSize: 104857600

deployment:
  isLocalDevelopment:  false
