# A static app's configuration file. Used for local debugging.
webhook:
  certRotatorConfiguration:
    secretName: "azure-defender-proxy-cert"
    serviceName: "azure-defender-proxy-service"
    webhookName: "azure-defender-proxy-mutating-webhook-configuration"
    caName: "azure-defender-proxy-ca"
    caOrganization: "azure-defender-proxy"
    certDir: "/certs"
    namespace: "kube-system"
  managerConfiguration:
    port: 8000
    certDir: "/certs"
  serverConfiguration:
    path: "/mutate"
    enableCertRotation: true
  handlerConfiguration:
    dryRun: false
    supportedKubernetesWorkloadResources: ["Pod","Deployment","ReplicaSet","StatefulSet","DaemonSet","Job","CronJob","ReplicationController"]
  extractorConfiguration:
    supportedKubernetesWorkloadResources: ["Pod","Deployment","ReplicaSet","StatefulSet","DaemonSet","Job","CronJob","ReplicationController"]

instrumentation:
  trace:
    tracerConfiguration:
      tracerLevel: 0
  tivan:
    tivanInstrumentationConfiguration:
      componentName: "debug-in-cluster-defense"
      azureResourceID: ""
      region: ""
      clusterDistribution: ""
      chartVersion: ""
      imageName: "local-development"
      imageVersion: "no-version"
      releaseTrain: ""
      nodeName: ""
      dirPath: "/var/log/azuredefender"
      mdmAccount: ""
      mdmNamespace: ""
      platformMdmAccount: ""
      platformMdmNamespace: ""

azdIdentity:
  envAzureAuthorizerConfiguration:
    mSIClientId: "" # This should be kept empty while you are running the service locally.

kubeletIdentity:
  envAzureAuthorizerConfiguration:
    mSIClientId: "" # This should be kept empty while you are running the service locally.

acr:
  craneWrappersConfiguration:
    retryPolicyConfiguration:
      retryAttempts: 3
      retryDurationInMS: 10

  tokenExchanger:
    retryPolicyConfiguration:
      retryAttempts: 3
      retryDurationInMS: 10

  acrTokenProviderConfiguration:
    # Expiration time in minutes of registryRefreshToken in cache
    registryRefreshTokenCacheExpirationTime: 10 # 10 minutes

arg:
  argClientConfiguration:
    # TODO change it to dynamic subscription that will be updated in the installation script.
    subscriptions: [ "4009f3ee-43c4-4f19-97e4-32b6f2285a68" ]

  argBaseClient:
    retryPolicyConfiguration:
      retryAttempts: 3
      retryDurationInMS: 100

  argDataProviderConfiguration:
    # Expiration time IN MINUTES of scan results in status unscanned in cache (redeploy will take at least a minute and scanning an image takes 4 minutes on average)
    cacheExpirationTimeUnscannedResults: 4 # 4 minute
    # Expiration time IN HOURS of scan results in status scanned in cache (need to sync with image-scan periodic scans - every 10 days)
    cacheExpirationTimeScannedResults: 24 # 24 hours

tag2digest:
  tag2DigestResolverConfiguration:
    # Expiration time IN MINUTES of digest in cache - changing image digest require editing source code, building image and pushing image. Longer than 2 minutes
    cacheExpirationTimeForResults: 2 # 2 minute

# Cache configuration
cache:
  redisClient:
    replicas: 1
    port: 6379
    targetport: 6379

    retryPolicyConfiguration:
      retryAttempts: 3
      retryDurationInMS: 10

  argDataProviderCacheConfiguration:
    address: "azure-defender-proxy-redis-service:6379"
    table: 0
    heartbeatFrequency: 5

  tokensCacheConfiguration:
    # In bytes, where 1024 * 1024 represents a single Megabyte, and 100 * 1024*1024 represents 100 Megabytes.
    cacheSize: 104857600 # 100 * 1024 * 1024
deployment:
  isLocalDevelopment: true
  namespace: "kube-system"

azdSecInfoProvider:
  GetContainersVulnerabilityScanInfoTimeoutDuration:
    timeDurationInMS: 10000

  azdSecInfoProviderConfiguration:
    # Expiration time IN MINUTES of timeout status in cache - 15 minutes in order to avoid multiple timeouts
    CacheExpirationTimeTimeout: 15 # 15 minutes
    # Expiration time IN SECONDS of containerVulnerabilityScanInfo in cache - 30 seconds in order to handle replica set (multiply requests on the same pod)
    CacheExpirationContainerVulnerabilityScanInfo: 30 # 30 seconds



