# A static app's configuration file. Used for local debugging.
webhook:
  CertRotatorConfiguration:
    SecretName: "azure-defender-proxy-cert"
    ServiceName: "azure-defender-proxy-service"
    WebhookName: "azure-defender-proxy-mutating-webhook-configuration"
    CaName: "azure-defender-proxy-ca"
    CaOrganization: "azure-defender-proxy"
    CertDir: "/certs"
    Namespace: "kube-system"
  ManagerConfiguration:
    Port: 8000
    CertDir: "/certs"
  ServerConfiguration:
    Path: "/mutate"
    EnableCertRotation: true
  HandlerConfiguration:
    DryRun: false
instrumentation:
  trace:
    TracerConfiguration:
      TracerLevel: 0
  tivan:
    TivanInstrumentationConfiguration:
      ComponentName: "azdproxy"
      MdmNamespace: "Tivan.Collector.Pods"

azdIdentity:
  EnvAzureAuthorizerConfiguration:
      IsLocalDevelopmentMode: true
      MSIClientId: "" # This should be kept empty while you are running the service locally.

kubeletIdentity:
  EnvAzureAuthorizerConfiguration:
    IsLocalDevelopmentMode: true
    MSIClientId: "" # This should be kept empty while you are running the service locally.

# Cache configuration
cache:
  redisClient:
    replicas: 1
    port: 6379
    targetport: 6379

  argDataProviderCacheConfiguration:
    Addr: "azure-defender-proxy-redis-service:6379"
    Db: 0

  tokensCacheConfiguration:
    # In bytes, where 1024 * 1024 represents a single Megabyte, and 100 * 1024*1024 represents 100 Megabytes.
    cacheSize: 104,857,600 # 100 * 1024 * 1024