# *** You will always be compliant with this policy if AzureDefenderInClusterDefense is not installed in your cluster.
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureDefenderBlockVulnerableImages
metadata:
  name: block-vulnerable-images
spec:
  match:
    kinds:
      - apiGroups: [ "","apps" ]
        kinds: [ "Pod","Deployment","ReplicaSet","StatefulSet","DaemonSet","Job","CronJob","ReplicationController" ]
  parameters:
    excludedImages: [ ]
    severityThresholdForExcludingNotPatchableFindings: "None"
    excludeFindingIDs: [ ]
    severity:
      High: 0
      Medium: 2
      Low: 3