// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	queries "github.com/Azure/AzureDefender-K8S-InClusterDefense/pkg/dataproviders/arg/queries"
	mock "github.com/stretchr/testify/mock"
)

// IARGQueryGenerator is an autogenerated mock type for the IARGQueryGenerator type
type IARGQueryGenerator struct {
	mock.Mock
}

// GenerateImageVulnerabilityScanQuery provides a mock function with given fields: queryParameters
func (_m *IARGQueryGenerator) GenerateImageVulnerabilityScanQuery(queryParameters *queries.ContainerVulnerabilityScanResultsQueryParameters) (string, error) {
	ret := _m.Called(queryParameters)

	var r0 string
	if rf, ok := ret.Get(0).(func(*queries.ContainerVulnerabilityScanResultsQueryParameters) string); ok {
		r0 = rf(queryParameters)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*queries.ContainerVulnerabilityScanResultsQueryParameters) error); ok {
		r1 = rf(queryParameters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
