// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	context "context"

	resourcegraph "github.com/Azure/azure-sdk-for-go/services/resourcegraph/mgmt/2021-03-01/resourcegraph"
	mock "github.com/stretchr/testify/mock"
)

// IARGBaseClientWrapper is an autogenerated mock type for the IARGBaseClientWrapper type
type IARGBaseClientWrapper struct {
	mock.Mock
}

// Resources provides a mock function with given fields: ctx, query
func (_m *IARGBaseClientWrapper) Resources(ctx context.Context, query resourcegraph.QueryRequest) (resourcegraph.QueryResponse, error) {
	ret := _m.Called(ctx, query)

	var r0 resourcegraph.QueryResponse
	if rf, ok := ret.Get(0).(func(context.Context, resourcegraph.QueryRequest) resourcegraph.QueryResponse); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(resourcegraph.QueryResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, resourcegraph.QueryRequest) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
