// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRegistryClient is an autogenerated mock type for the IRegistryClient type
type IRegistryClient struct {
	mock.Mock
}

// GetDigest provides a mock function with given fields: imageRef
func (_m *IRegistryClient) GetDigest(imageRef string) (string, error) {
	ret := _m.Called(imageRef)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(imageRef)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(imageRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
