apiVersion: v1
kind: Pod
metadata:
  name: healthy-pod
  namespace: default
spec:
  containers:
    - name: healthy-container
      image: blockregistrydev.azurecr.io/azdproxy-image-debugging:7238f81-dirty