apiVersion: v1
kind: Pod
metadata:
  name: healthy-pod
  namespace: default
  annotations:
    azuredefender.io/containers.vulnerability.scan.info: "{\"containers\":[{\"name\":\"testContainer\",\"image\":{\"name\":\"tomer.azurecr.io/core/app:4.6\",\"digest\":\"sha256:4a\"},\"scanStatus\":\"healthyScan\",\"scanFindings\":[]}]}"
    credScan.scan.info: "{\"generatedTimestamp\":\"2021-09-21T17:36:39.7945965Z\",\"CredScanInfo\":[]}"
spec:
  containers:
    - name: healthy-container
      image: alpine
