#------------------------------------------------------------
# Copyright (c) Microsoft Corporation.  All rights reserved.
#------------------------------------------------------------
apiVersion: v2
name: azdproxy
description: A Helm chart for AzDProxy
type: application
version: "0.0.1"
appVersion: "1.0.0"
home: https://github.com/Azure/AzureDefender-K8S-InClusterDefense
sources:
  - https://github.com/Azure/AzureDefender-K8S-InClusterDefense.git