# Default values for AzDProxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
AzDProxy:
  # -- common prefix name for all resources.
  prefixResourceDeployment: azure-defender-proxy
  # Webhook values
  webhook:
    # -- Amount of replicas of azdproxy.
    replicas: 3
    # Image values:
    image:
      # -- Official image.
      name: "azdproxy-image"
      # -- Default for always. in case that you want to use local registry, change to 'Never'.
      pullPolicy: "Always"
    # -- The path that the webhook handler will be listening on.
    mutationPath: "/mutate"
    # Volume values of webhook.
    volume:
      # -- The name of the volume.
      name: "cert"
      # -- The mount path of the volume.
      mountPath: "/certs"
    # Configuration values of Cert Rotator.
    CertRotatorConfiguration:
      # -- secret name
      SecretName: "cert"
      # -- service name
      ServiceName: "service"
      # -- webhook name
      WebhookName: "mutating-webhook-configuration"
      # -- ca name
      CaName: "ca"
    # Configuration values of Cert Rotator.
    ServerConfiguration:
      # -- is the run on dry mode
      RunOnDryRunMode: false
      # -- is the cert rotation enabled
      EnableCertRotation: true

    # -- The resources of the webhook.
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  # Values of mutation-configuration.yaml file:
  webhook_configuration:
    # -- Webhook timeout in seconds
    timeoutSeconds: 3

  # Values of service.yaml file.
  service:
    # -- The port on which the service will send requests to, so the webhook be listening on.
    targetPort: 8000

  # Values for App's configuration.
  configuration:
    # Volume values of webhook.
    volume:
      # -- The name of the volume.
      name: "config"
      # -- The mount path of the volume.
      mountPath: "/configs"

  # Instrumentation values
  instrumentation:
    # Values for App's configuration.
    LoggerCondifuration:
      logLevel: "INFO"
      logLevelKey: "level"
      logLevelEncoder: "lower"
