# Default values for AzDProxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
azDProxy:
  # -- common prefix name for all resources.
  prefixResourceDeployment: azure-defender-proxy
  # Webhook values
  webhook:
    # -- Amount of replicas of azdproxy.
    replicas: 3
    # Image values:
    image:
      # -- Official image.
      name: "azdproxy-image"
      # -- Default for always. in case that you want to use local registry, change to 'Never'.
      pullPolicy: "Always"
    # -- The path that the webhook handler will be listening on.
    mutationPath: "/mutate"
    # Volume values of webhook.
    volume:
      # -- The name of the volume.
      name: "cert"
      # -- The mount path of the volume.
      mountPath: "/certs"
    # Configuration values of Cert Rotator.
    certRotatorConfiguration:
      # -- secret name
      secretName: "cert"
      # -- service name
      serviceName: "service"
      # -- webhook name
      webhookName: "mutating-webhook-configuration"
      # -- ca name
      caName: "ca"
    # Configuration values of server.
    serverConfiguration:
      # -- is the cert rotation enabled.
      enableCertRotation: true
    # Configuration values of handler.
    handlerConfiguration:
      # -- is the run on dry mode.
      runOnDryRunMode: false

    # -- The resources of the webhook.
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  # Values of mutation-configuration.yaml file:
  webhook_configuration:
    # -- Webhook timeout in seconds
    timeoutSeconds: 3

  # Values of service.yaml file.
  service:
    # -- The port on which the service will send requests to, so the webhook be listening on.
    targetPort: 8000

  # Values for App's configuration mounting.
  configuration:
    # Volume values of webhook.
    volume:
      # -- The name of the volume.
      name: "config"
      # -- The mount path of the volume.
      mountPath: "/config"
    # Path of the configuration file
    filePath: "/config/appConfig.yaml"

  # Instrumentation values
  instrumentation:

    # Tivan values
    tivan:
      # Values for Tivan's instrumentation configuration:
      tivanInstrumentationConfiguration:
        mdmNamespace: "Tivan.Collector.Pods"

    # Trace values
    trace:
      # Values for tracer's configuration:
      tracerConfiguration:
        tracerLevel: 0

  # Azure Auth values
  azdIdentity:
    envAzureAuthorizerConfiguration:
      mSIClientId: "a554f933-695f-4ecf-abe4-2a7515e8c1b7"

  kubeletIdentity:
    envAzureAuthorizerConfiguration:
      mSIClientId: "4446918a-1c6c-437e-9db1-018acb52efdc"

  deployment:
    isLocalDevelopment: false

  # ACR policy values
  acr:
    craneWrappers:
      retryPolicyConfiguration:
        # Number of retry attempts
        retryAttempts: 3
        # Sleep duration between retries (in milliseconds):
        retryDuration: "10ms"

  # ARG values
  arg:
    argBaseClient:
      retryPolicyConfiguration:
        # Number of retry attempts
        retryAttempts: 3
        # Sleep duration between retries (in milliseconds):
        retryDuration: "100ms"

  # CredScan
  # -- common prefix name for all resources sidecar.
  prefixResourceDeploymentSideCar: azure-defender-proxy-sidecar
  # Image values:
  imageSideCar:
    # -- Official image.
    name: "credscanwebapi.azurecr.io/crescanwebapi"
    # -- Default for always. in case that you want to use local registry, change to 'Never'.
    pullPolicy: "Always"