# Default values for  dev environment AzDProxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
AzDProxy:
  # -- common prefix name for all resources.
  prefixResourceDeployment: azure-defender-proxy
  # Webhook values
  webhook:
    # -- Amount of replicas of azdproxy.
    replicas: 1
    # Image values:
    image:
      # -- Official image.
      name: "azdproxy-image"
      # -- Default for Always. in case that you want to use local registry, change to 'Never'.
      pullPolicy: "Always"
    # -- The path that the webhook handler will be listening on.
    mutationPath: "/mutate"
    # Volume values of webhook.
    volume:
      # -- The name of the volume.
      name: "cert"
      # -- The mount path of the volume.
      mountPath: "/certs"
    # Configuration values of Cert Rotator.
    certRotatorConfiguration:
      # -- secret name
      secretName: "cert"
      # -- service name
      serviceName: "service"
      # -- webhook name
      webhookName: "mutating-webhook-configuration"
      # -- ca name
      caName: "ca"
    # Configuration values of server.
    serverConfiguration:
      # -- is the cert rotation enabled.
      enableCertRotation: true
    # Configuration values of handler.
    handlerConfiguration:
      # -- is the run on dry mode.
      runOnDryRunMode: false

    # -- The resources of the webhook.
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  # Values of mutation-configuration.yaml file:
  webhook_configuration:
    # -- Webhook timeout in seconds
    timeoutSeconds: 10

  # Values of service.yaml file.
  service:
    # -- The port on which the service will send requests to, so the webhook be listening on.
    targetPort: 8000

  # Values for App's configuration mounting.
  configuration:
    # Volume values of webhook.
    volume:
      # -- The name of the volume.
      name: "config"
      # -- The mount path of the volume.
      mountPath: "/config"
    # Path of the configuration file
    filePath: "/config/appConfig.yaml"

  # Instrumentation values
  instrumentation:

    # Tivan values
    tivan:
      # Values for Tivan's instrumentation configuration:
      tivanInstrumentationConfiguration:
        componentName: "azure-defender-proxy"
        azureResourceID: ""
        region: ""
        clusterDistribution: ""
        chartVersion: ""
        releaseTrain: ""
        nodeName: ""
        dirPath: "/var/log/azuredefender"
        mdmAccount: ""
        mdmNamespace: ""
        platformMdmAccount: ""
        platformMdmNamespace: ""

    # Trace values
    trace:
      # Values for tracer's configuration:
      tracerConfiguration:
        tracerLevel: 0

  # Azure Auth values
  azdIdentity:
    envAzureAuthorizerConfiguration:
      mSIClientId: ""

  kubeletIdentity:
    envAzureAuthorizerConfiguration:
      mSIClientId: ""

  deployment:
    isLocalDevelopment: false

  # ACR policy values
  acr:

    craneWrappers:
      retryPolicyConfiguration:
        # Number of retry attempts
        retryAttempts: 3
        # Sleep duration between retries (in milliseconds):
        retryDurationInMS: 10

    tokenExchanger:
      retryPolicyConfiguration:
        # Number of retry attempts
        retryAttempts: 3
        # Sleep duration between retries (in milliseconds):
        retryDurationInMS: 10

  # ARG values
  arg:

    argClientConfiguration:
      subscriptions: [ ]

    argBaseClient:
      retryPolicyConfiguration:
        # Number of retry attempts
        retryAttempts: 3
        # Sleep duration between retries (in milliseconds):
        retryDurationInMS: 100

  # Cache configuration
  cache:
    nonInMem:
      deploymentConfiguration:
        # Data structure store used for cache
        app: redis
        #  -- Image of redis containers
        image: redis:6
        # -- amount of replicas of redis
        replicas: 1
        # -- the port that redis cache will be listened.
        port: 6379
      client:
        clientConfiguration:
          # -- Address that the client will listen to (=app's service). Will be set to prefixResourceDeployment + address + port.
          address: "redis-service"
          # -- The table (Db) that the argDataProviderCache will save to data.
          argDataProviderCacheTable: 0
          # -- The table (Db) that the tag2digestCache will save to data.
          tag2digestCacheTable: 1
        retryPolicyConfiguration:
          #  -- Number of retry attempts
          retryAttempts: 3
          #  -- Sleep duration between retries (in milliseconds):
          retryDuration: 10
          #  -- Timeunit for the backoff duration
          timeUnit: "ms"

    inMem:
      tokensCacheConfiguration:
        # In bytes, where 1024 * 1024 represents a single Megabyte, and 100 * 1024*1024 represents 100 Megabytes.
        cacheSize: 104857600 # 100 * 1024 * 1024

  azdSecInfoProvider:
    GetContainersVulnerabilityScanInfo:
      timeout:
        timeDurationInMS: 2500

