# Default values for AzDProxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
AzDProxy:
  # -- common prefix name for all resources.
  prefixResourceDeployment: azure-defender-proxy
  # Webhook values
  webhook:
    # -- Amount of replicas of azdproxy.
    replicas: 3
    # Image values:
    image:
      # -- Official image.
      name: "azdproxy-image"
      # -- Default for always. in case that you want to use local registry, change to 'Never'.
      pullPolicy: "Always"
    # -- The path that the webhook handler will be listening on.
    mutationPath: "/mutate"
    # Volume values of webhook.
    volume:
      # -- The name of the volume.
      name: "cert"
      # -- The mount path of the volume.
      mountPath: "/certs"
    # Configuration values of Cert Rotator.
    CertRotatorConfiguration:
      # -- secret name
      SecretName: "cert"
      # -- service name
      ServiceName: "service"
      # -- webhook name
      WebhookName: "mutating-webhook-configuration"
      # -- ca name
      CaName: "ca"
    # Configuration values of server.
    ServerConfiguration:
      # -- is the cert rotation enabled.
      EnableCertRotation: true
    # Configuration values of handler.
    HandlerConfiguration:
      # -- is the run on dry mode.
      RunOnDryRunMode: false

    # -- The resources of the webhook.
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  # Values of mutation-configuration.yaml file:
  webhook_configuration:
    # -- Webhook timeout in seconds
    timeoutSeconds: 3

  # Values of service.yaml file.
  service:
    # -- The port on which the service will send requests to, so the webhook be listening on.
    targetPort: 8000

  # Values for App's configuration mounting.
  configuration:
    # Volume values of webhook.
    volume:
      # -- The name of the volume.
      name: "config"
      # -- The mount path of the volume.
      mountPath: "/config"
    # Path of the configuration file
    filePath: "/config/AppConfig.yaml"

  # Instrumentation values
  instrumentation:

    # Tivan values
    tivan:
      # Values for Tivan's instrumentation configuration:
      TivanInstrumentationConfiguration:
        MdmNamespace: "Tivan.Collector.Pods"

    # Trace values
    trace:
      # Values for tracer's configuration:
      TracerConfiguration:
        TracerLevel: 0

  # Azure Auth values
  azureauth:
    envAzureAuthorizerConfiguration:
      IsLocalDevelopmentMode: false
      MSIClientId: "a554f933-695f-4ecf-abe4-2a7515e8c1b7"

  # Wrappers policy values
  wrappers:
    craneWrappers:
      RetryPolicyConfiguration:
        # Number of retries in case method has failed
        retryCount: 3
        # Sleep duration between retries (in milliseconds):
        SleepDurationBetweenRetries: 500

  # Arg values
  arg:
    ArgBaseClient:
      RetryPolicyConfiguration:
        # Number of retries in case method has failed
        retryCount: 3
        # Sleep duration between retries (in milliseconds):
        SleepDurationBetweenRetries: 500