// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	contracts "github.com/Azure/AzureDefender-K8S-InClusterDefense/pkg/azdsecinfo/contracts"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// IAzdSecInfoProvider is an autogenerated mock type for the IAzdSecInfoProvider type
type IAzdSecInfoProvider struct {
	mock.Mock
}

// GetContainerVulnerabilityScanInfo provides a mock function with given fields: _a0
func (_m *IAzdSecInfoProvider) GetContainerVulnerabilityScanInfo(_a0 *v1.Container) (*contracts.ContainerVulnerabilityScanInfo, error) {
	ret := _m.Called(_a0)

	var r0 *contracts.ContainerVulnerabilityScanInfo
	if rf, ok := ret.Get(0).(func(*v1.Container) *contracts.ContainerVulnerabilityScanInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contracts.ContainerVulnerabilityScanInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1.Container) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
