// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	authn "github.com/google/go-containerregistry/pkg/authn"

	mock "github.com/stretchr/testify/mock"
)

// IACRKeychainFactory is an autogenerated mock type for the IACRKeychainFactory type
type IACRKeychainFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: registry
func (_m *IACRKeychainFactory) Create(registry string) (authn.Keychain, error) {
	ret := _m.Called(registry)

	var r0 authn.Keychain
	if rf, ok := ret.Get(0).(func(string) authn.Keychain); ok {
		r0 = rf(registry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authn.Keychain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(registry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
