// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	authn "github.com/google/go-containerregistry/pkg/authn"

	mock "github.com/stretchr/testify/mock"
)

// IK8SKeychainFactory is an autogenerated mock type for the IK8SKeychainFactory type
type IK8SKeychainFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: namespace, imagePullSecrets, serviceAccountName
func (_m *IK8SKeychainFactory) Create(namespace string, imagePullSecrets []string, serviceAccountName string) (authn.Keychain, error) {
	ret := _m.Called(namespace, imagePullSecrets, serviceAccountName)

	var r0 authn.Keychain
	if rf, ok := ret.Get(0).(func(string, []string, string) authn.Keychain); ok {
		r0 = rf(namespace, imagePullSecrets, serviceAccountName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authn.Keychain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string, string) error); ok {
		r1 = rf(namespace, imagePullSecrets, serviceAccountName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
