// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IARGClient is an autogenerated mock type for the IARGClient type
type IARGClient struct {
	mock.Mock
}

// QueryResources provides a mock function with given fields: query
func (_m *IARGClient) QueryResources(query string) ([]interface{}, error) {
	ret := _m.Called(query)

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func(string) []interface{}); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
