name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-test-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v ./...


  build-secure-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: docker build -t azuredefendermcrdev.azurecr.io/public/azuredefender/dev/in-cluster-defense:${{ github.sha }} -f ../build/Dockerfile .

      - uses: Azure/container-scan@v0
        with:
          image-name: azuredefendermcrdev.azurecr.io/public/azuredefender/dev/in-cluster-defense:${{ github.sha }}

      - uses: Azure/docker-login@v1
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.DEV_REGISTRY_USERNAME }}
          password: ${{ secrets.DEV_REGISTRY_PASSWORD }}

      - run: docker push azuredefendermcrdev.azurecr.io/public/azuredefender/dev/in-cluster-defense:${{ github.sha }}
